//json-server --watch --port 3333 src/db.json 

GET http://localhost:3333/cursos

###

GET http://localhost:3333/cursos/2 HTTP/1.1

###

POST http://localhost:3333/cursos HTTP/1.1
content-type: application/json

{
    "nome": "Java"
}

###

PUT http://localhost:3333/cursos/2 HTTP/1.1
content-type: application/json

{
    "nome": "Java OO"
}